services:
  bot:
    container_name: "bot"
    build: ./
    command: sh -c "alembic upgrade head && python main.py"
    env_file:
      - ./.env.dev
    volumes:
      - ./logs:/app/logs/
    depends_on:
      postgresdb:
        condition: service_healthy
#      - postgresdb
    restart: on-failure

  postgresdb:
    image: postgres:13.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1GB
        reservations:
          cpus: "0.5"
          memory: 512M
    command: >
      postgres -c max_connections=500
               -c shared_buffers=512MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=128MB
               -c checkpoint_completion_target=0.9
               -c wal_buffers=16MB
  redis:
    image: redis:latest
    container_name: "redis_container"
    env_file:
      - ./.env.dev
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: >
      sh -c '
      mkdir -p /usr/local/etc/redis &&
      echo "requirepass $$REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
      echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
      redis-server /usr/local/etc/redis/redis.conf
      '
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
